### ISSUE TITLE
#11 - Desenhar a tela Tipos Sanguíneos

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc-2024#11]
Nesta tela deve conter o código, descrição, estoque, estoque mínimo e fator RH. O fator Rh pode ser um combobox com as informações fixas, neste caso Positivo e Negativo. Além dos campos Cadastrar, Alterar, Excluir, Limpar, Fechar e Pesquisar. Também deve conter a tabela para listar os dados do banco.

**Comment by omenegazzi** [comment]
Adicionar o campo e o botão de pesquisa.

**Comment by mateuseger** [comment]
Realizado a alteração conforme orientado.
