### ISSUE TITLE
#15 - Desenhar tela de Agendamento de doação

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc-2024#15]
Nesta tela irá conter o código do agendamento, data, hora e o doador. Além dos campos Cadastrar, Alterar, Excluir, Limpar, Fechar e Pesquisar. Também deve conter a tabela para listar os dados do banco.

**Comment by omenegazzi** [comment]
A tela de agendamento o filtro deve ser um campo combobox e foi adicionado um jSmenu.

**Comment by HeberRodriguez2024** [comment]
alteração feita
