### ISSUE TITLE
#7 - Desenhar layout de tela de login

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc-2024#7]
Está será a tela principal do sistema. Está tela a principio irá conter dois campos com entrada de dados uma será para o login e outro para a senha e um botão para entrar.

**Comment by omenegazzi** [comment]
A tela de login não foi enviado junto na branch. Provavelmente apenas foi criado o branch (ramificação) e faltou adicionar e fazer o commit da tela.

**Comment by HeberRodriguez2024** [comment]
Foi realizada alterçao da tela
