### ISSUE TITLE
#73 - Desenhar a tela produtos

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc-2024#81]
A tela de produtos deverá conter os seguintes campos: código, descrição, tipo(combobox: ex. Materia-prima, uso e consumo equipamento e etc.), data de aquisição, estado do produto (Combobox: ex: 'Em uso', 'Manutenção', 'Desativado etc), data da ultima manutenção.

**Comment by omenegazzi** [comment]
A tela de produtos está faltando informações. Por exemplo, não possui os botões de cadastrar, alterar, excluir e pesquisar. Também falta ter a tabela para listar os dados.

**Comment by Garcia-stark** [comment]
Você pode criar uma outra tarefa #??, para criar a função pesquisar. Não tem, nas tarefas, e na tela inseri um botão para pesquisar.
